application: amelia-reiser
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: assets/index.html
  upload: assets/index.html

- url: /about
  static_files: assets/about.html
  upload: assets/about.html

- url: /resume
  static_files: assets/resume.html
  upload: assets/resume.html

- url: /gallery
  static_files: assets/gallery.html
  upload: assets/gallery.html

- url: /contact
  static_files: assets/contact.html
  upload: assets/contact.html

- url: /
  static_dir: assets
